"use client";

import { SIGNATURE_FONTS_STYLESHEET } from "@/lib/signature-fonts-url";

/**
 * Injects the signature webfont stylesheets and resolves once they are applied.
 *
 * Any page that rasterises a saved signature needs these — not just Studio.
 * Without them `ctx.font` silently falls back to a generic cursive, so the
 * Cloud Library, the Sign PDF picker, and the signature stamped into the
 * exported PDF all came out in the wrong typeface.
 */

let pending: Promise<void> | null = null;

function loadSheet(href: string): Promise<void> {
  const existing = document.querySelector<HTMLLinkElement>(
    `link[data-inkflow-fonts="${href}"]`,
  );
  if (existing) return Promise.resolve();

  return new Promise((resolve) => {
    const link = document.createElement("link");
    link.rel = "stylesheet";
    link.href = href;
    link.dataset.inkflowFonts = href;
    // Resolve either way: a failed sheet must not hang the caller forever.
    link.onload = () => resolve();
    link.onerror = () => resolve();
    document.head.appendChild(link);
  });
}

function ensurePreconnect() {
  if (document.querySelector('link[data-inkflow-preconnect="gfonts"]')) return;
  const api = document.createElement("link");
  api.rel = "preconnect";
  api.href = "https://fonts.googleapis.com";
  api.dataset.inkflowPreconnect = "gfonts";
  document.head.appendChild(api);

  const statics = document.createElement("link");
  statics.rel = "preconnect";
  statics.href = "https://fonts.gstatic.com";
  statics.crossOrigin = "";
  document.head.appendChild(statics);
}

export function ensureSignatureFonts(): Promise<void> {
  if (typeof document === "undefined") return Promise.resolve();
  if (!pending) {
    ensurePreconnect();
    pending = Promise.all([
      loadSheet(SIGNATURE_FONTS_STYLESHEET),
      // Local "art" faces, generated by scripts/import-art-fonts.mjs.
      loadSheet("/fonts/art-fonts.css"),
    ]).then(() => undefined);
  }
  return pending;
}

/**
 * Guarantees a specific family is ready to draw on a canvas.
 *
 * `document.fonts.ready` is not enough: a webfont nothing on the page uses is
 * never even requested, so ready resolves immediately while the face is still
 * unloaded. `document.fonts.load` requests that exact face.
 */
export async function ensureFontReady(
  fontFamily: string,
  sizePx: number,
): Promise<void> {
  await ensureSignatureFonts();
  if (typeof document === "undefined" || !("fonts" in document)) return;
  try {
    await document.fonts.load(`${Math.round(sizePx)}px ${fontFamily}`);
    await document.fonts.ready;
  } catch {
    // Font unavailable — rendering falls back, which is still better than
    // blocking the export.
  }
}
