import type { Config } from "tailwindcss";

/**
 * Design tokens ported from the Stitch "Artisan Signature Warmth" design system.
 * Editorial-minimalist, tactile, warm cream + sepia palette.
 */
const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#454742",
        "on-tertiary-fixed": "#261900",
        "inverse-surface": "#32302a",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#4b4642",
        "inverse-on-surface": "#f5f0e7",
        "surface-container-low": "#f8f3ea",
        "tertiary-container": "#fffaf8",
        "on-primary-fixed": "#1b1c1a",
        "on-surface": "#1d1c16",
        outline: "#767872",
        background: "#fef9ef",
        "on-error": "#ffffff",
        "surface-dim": "#ded9d1",
        "on-secondary-fixed": "#1e1b18",
        "on-error-container": "#93000a",
        "inverse-primary": "#c8c6c3",
        "surface-bright": "#fef9ef",
        "surface-container": "#f2ede4",
        "on-tertiary-fixed-variant": "#5d4201",
        "error-container": "#ffdad6",
        "on-secondary-container": "#67625e",
        primary: "#5e5e5c",
        tertiary: "#775a19",
        "surface-container-highest": "#e7e2d9",
        "primary-container": "#fdfbf7",
        "tertiary-fixed": "#ffdea5",
        "outline-variant": "#c6c7c0",
        "primary-fixed": "#e4e2de",
        "surface-container-high": "#ede8df",
        "secondary-fixed-dim": "#cdc5c0",
        "on-primary-container": "#747471",
        secondary: "#635d5a",
        "on-primary-fixed-variant": "#474744",
        "surface-variant": "#e7e2d9",
        "tertiary-fixed-dim": "#e9c176",
        "on-background": "#1d1c16",
        surface: "#fef9ef",
        "on-tertiary": "#ffffff",
        "surface-tint": "#5e5e5c",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#8f6e2d",
        "primary-fixed-dim": "#c8c6c3",
        "secondary-fixed": "#e9e1dc",
        error: "#ba1a1a",
        "secondary-container": "#e6ded9",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        xs: "4px",
        lg: "24px",
        "container-max": "1120px",
        sm: "8px",
        md: "16px",
        unit: "4px",
        xl: "40px",
        xxl: "64px",
      },
      maxWidth: {
        "container-max": "1120px",
      },
      fontFamily: {
        "headline-sm": ["var(--font-libre-caslon)", "serif"],
        "headline-md": ["var(--font-libre-caslon)", "serif"],
        "display-lg": ["var(--font-libre-caslon)", "serif"],
        "display-lg-mobile": ["var(--font-libre-caslon)", "serif"],
        "body-md": ["var(--font-hanken)", "sans-serif"],
        "body-lg": ["var(--font-hanken)", "sans-serif"],
        "label-md": ["var(--font-hanken)", "sans-serif"],
        "label-sm": ["var(--font-hanken)", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "500" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "display-lg-mobile": ["36px", { lineHeight: "44px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
